---
# Title: 01-ansible-server.yml
#
# Author: bitfinity - L. Rutten
# Owner: bitfinity - IT Operations
#
# File: tasks/01-ansible-core.yml
#
# Description:
#   Taskfile for configuring Ansible server.
#
- name: "Create Ansible security group"
  ansible.builtin.group:
    name: ansible

- name: "Create Ansible user"
  ansible.builtin.user:
    name: ansible
    shell: /bin/bash
    group: ansible
    groups: sudo
    append: yes
    generate_ssh_key: yes
    ssh_key_file: .ssh/id_ed25519
    ssh_key_type: ed25519
    
- name: "Add Ansible user to sudoers"
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/ansible
    line: "ansible ALL=NOPASSWD: ALL"
    owner: root
    group: root
    mode: 0440
    create: yes

- name: "Ensure file /home/ansible/.ansible-vault exists and set correct file permissions"
  ansible.builtin.lineinfile:
    path: /etc/.ansible-vault
    line: "{{ semui_ansible_vault_pass }}"
    owner: root
    group: ansible
    mode: 0640
    create: yes

- name: "Check if /home/ansible/.ssh/authorized_keys exists"
  ansible.builtin.stat:
    path: /home/ansible/.ssh/authorized_keys
  register: result_authorized_keys

- name: "Ensure file /home/ansible/.ssh/authorized_keys exists and set correct file permissions"
  ansible.builtin.file:
    path: /home/ansible/.ssh/authorized_keys
    state: touch
    owner: ansible
    group: ansible
    mode: 0600

- name: "Transfer publickey id_ed25519.pub to Ansible user on localhost"
  ansible.builtin.raw: cat /home/ansible/.ssh/id_ed25519.pub >> /home/ansible/.ssh/authorized_keys
  when: not result_authorized_keys.stat.exists
