---
# Title: 01-ansible-server.yml
#
# Author: bitfinity-nl - L. Rutten
# Owner: IT Operations
# File: tasks/01-ansible-server.yml
#
# Description:
#   Taskfile for configuring Ansible server.

- name: "Create Ansible security group"
  ansible.builtin.group:
    name: ansible

- name: "Create Ansible user"
  ansible.builtin.user:
    name: ansible
    shell: /bin/bash
    group: ansible
    groups: sudo
    append: yes
    generate_ssh_key: yes
    
- name: "Add Ansible user to sudoers"
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/ansible
    line: "ansible ALL=NOPASSWD: ALL"
    owner: root
    group: root
    mode: 0440
    create: yes
    
- name: "Transfer publickey to Ansible user on localhost"
  raw: "cat /home/ansible/.ssh/id_rsa.pub >> /home/ansible/.ssh/authorized_keys"

- name: "Set permissions on ~/.ssh/authorized_keys for user Ansible"
  ansible.builtin.file:
    path: /home/ansible/.ssh/authorized_keys
    owner: ansible
    group: ansible
    mode: '0600'
