---
# Title: role-ansible-semaphore
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: tasks/main.yml
#
# Description:
#  This role contains the tasks to install a
#  Ansible Semaphore server. 

- name: "Install APT packages (dependencies)"
  apt:
    pkg:
    - docker.io
    - python3-docker
    - python3-pip

- name: Install docker-compose python package
  pip:
    name: docker-compose
    
- name: "Pull Docker image Semaphore"
  docker_image:
    name:  ansiblesemaphore/semaphore:latest
    source: pull

- name: "Create directory for local ansible-semaphore /opt/docker/ansiblesemaphore/data/"
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  loop:
    - { path: /opt/docker/ansiblesemaphore/, owner: 'root', group: 'root', mode: '0755' }
    - { path: /opt/docker/ansiblesemaphore/data, owner: 'root', group: 'root', mode: '0777' }
    - { path: /opt/docker/ansiblesemaphore/authorized-keys, owner: 'root', group: 'root', mode: '0777' }
    - { path: /opt/docker/ansiblesemaphore/config, owner: 'root', group: 'root', mode: '0777' }
    - { path: /opt/docker/ansiblesemaphore/inventory, owner: 'root', group: 'root', mode: '0777' }
    
- name: "Check if /opt/docker/ansiblesemaphore/.semaphore_encryption_key exist"
  stat:
    path: "/opt/docker/ansiblesemaphore/semaphore_encryption_key"
  register: semaphore_encryption_key

- name: "Generate ansible semaphore encryption key"
  raw: "head -c32 /dev/urandom | base64 > /opt/docker/ansiblesemaphore/semaphore_encryption_key"
  when: semaphore_encryption_key.stat.exists == False

- name: "Set correct permissions on /opt/docker/ansiblesemaphore/semaphore_encryption_key"
  ansible.builtin.file:
    path: "/opt/docker/ansiblesemaphore/semaphore_encryption_key"
    owner: root
    group: root
    mode: '0600'

- name: "Put encryption key in variable"
  set_fact:
    semaphore_encryption_key: "{{ lookup('file','/opt/docker/ansiblesemaphore/semaphore_encryption_key') }}"    
  
- name: "Transfer template(s)"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'docker-compose.yml.j2', dest: '/opt/docker/ansiblesemaphore/docker-compose.yml' }

- name: "Docker Compose UP"
  docker_compose:
    project_src: /opt/docker/ansiblesemaphore/
    build: no
