---
# Title: Apache2 (local) reverse proxy
#
# Author: Bitfinity-NL / L. Rutten
# Owner: Bitfinity-NL / L. Rutten
#
# File: tasks/03-apache2.yml
#
# Description:
#   This taskfile contains the tasks
#   configuring the local reverse proxy.
#
- name: "Install APT packages"
  ansible.builtin.apt:
    pkg:
    - apache2

- name: "Apache2 load modules"
  community.general.apache2_module:
    state: present
    name: "{{ item }}"
  loop:
    - proxy
    - proxy_http
    - rewrite
    - ssl

- name: "Transfer templates"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: 'templates/apache2.conf.j2', dest: '/etc/apache2/sites-available/{{ apache2_application_name }}.conf' }

- name: "Disable default Apache2 sites"
  ansible.builtin.command: "a2dissite {{ item }}"
  loop:
    - 000-default.conf
    - default-ssl.conf 
    - 000-default-le-ssl.conf
  notify:
    - restart_apache2

- name: "Enable {{ apache2_application_name }}.conf"
  ansible.builtin.command: a2ensite {{ apache2_application_name }}.conf
  notify: restart_apache2
