---
# Title: role-ansible-semaphore
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: tasks/main.yml
#
# Description:
#  This role contains the tasks to install a
#  Ansible Semaphore server. 

- name: "Install APT packages (dependencies)"
  apt:
    pkg:
    - docker.io
    - python3-docker
    - python3-pip


- name: Install docker-compose python package
  pip:
    name: docker-compose
    
- name: "Pull Docker image Semaphore"
  docker_image:
    name:  ansiblesemaphore/semaphore:latest
    source: pull

- name: "Create directory for local ansible-semaphore /opt/docker/ansiblesemaphore/data/"
  file:
    path: /opt/docker/ansiblesemaphore/data/
    state: directory


#---
- name: "Check if /opt/invoiceninja_api_key exist"
  stat:
    path: "/opt/invoiceninja_api_key"
  register: invoiceninja_api_key_file

#- name: "Generate API_KEY"
#  raw: "/opt/invoiceninja_api_key.sh"
#  when: invoiceninja_api_key_file.stat.exists == False

#- name: "Put API_KEY in variable"
#  set_fact:
#    invoiceninja_api_key: "{{ lookup('file','/tmp/invoiceninja_api_key') }}"    

#--
  
- name: "Transfer template(s)"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'docker-compose.yml.j2', dest: '/opt/docker/ansiblesemaphore/docker-compose.yml' }

- name: "Docker Compose UP"
  docker_compose:
    project_src: /opt/docker/ansiblesemaphore/
    build: no
