---
#
#
# Source(s):
#   - https://computingforgeeks.com/install-semaphore-ansible-web-ui-on-ubuntu-debian/
#
- name: "nstall Ansible-Semaphore via .deb package from the internet"
  ansible.builtin.apt:
    deb: https://example.com/python-ppq_0.1-1_all.deb


    
