---
# Title: Ansible Semaphore Binary package
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: tasks/semaphore-package.yml
#
# Source(s):
#   - https://computingforgeeks.com/install-semaphore-ansible-web-ui-on-ubuntu-debian/
#
- name: "Install Ansible-Semaphore via .deb binary package from the internet"
  ansible.builtin.apt:
    deb: https://github.com/ansible-semaphore/semaphore/releases/download/v{{ sem_deb_release }}/semaphore_2.8.75_linux_amd64.deb

- name: "Run semaphore setup silent"

- name: "Transfer templates"
  ansible.builtin.template:
    src: "{{ item.src: }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0755'
  loop:
    - { src: 'templates/semaphore.service.j2',
        dest: '/etc/systemd/system/semaphore.service',
        ower: 'root',
        group: 'root',
        mode: '0755',
        desc: 'Configure Systemd for Semaphore Ansible UI' }
        
- name: ""
