---
# Title: Ansible Semaphore Binary package
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: tasks/semaphore-package.yml
#
# Source(s):
#   - https://computingforgeeks.com/install-semaphore-ansible-web-ui-on-ubuntu-debian/
#
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /opt/ansible-semaphore
    state: directory
    mode: '0750'

- name: "Check if /opt/ansible-semaphore/semaphore_cookie_hash exist"
  stat:
    path: "/opt/ansible-semaphore/semaphore_cookie_hash"
  register: semaphore_cookie_hash_result
  
- name: "Generate ansible semaphore cookie hash"
  raw: "head -c32 /dev/urandom | base64 > /opt/ansible-semaphore/semaphore_cookie_hash"
  when: semaphore_cookie_hash_result.stat.exists == False

- name: "Put cookie hash in variable"
  set_fact:
    semaphore_cookie_hash: "{{ lookup('file','/opt/ansible-semaphore/semaphore_cookie_hash') }}"  
    
- name: "Check if /opt/ansible-semaphore/semaphore_cookie_encryption exist"
  stat:
    path: "/opt/ansible-semaphore/semaphore_cookie_encryption"
  register: semaphore_cookie_encryption_result
  
- name: "Generate ansible semaphore cookie encryption"
  raw: "head -c32 /dev/urandom | base64 > /opt/ansible-semaphore/semaphore_cookie_encryption"
  when: semaphore_cookie_encryption_result.stat.exists == False

- name: "Put cookie encryption in variable"
  set_fact:
    semaphore_cookie_encryption: "{{ lookup('file','/opt/ansible-semaphore/semaphore_cookie_encryption') }}"  
 
- name: "Check if /opt/ansible-semaphore/semaphore_encryption_key exist"
  stat:
    path: "/opt/ansible-semaphore/semaphore_encryption_key"
  register: semaphore_encryption_key_result
  
- name: "Generate ansible semaphore encryption key"
  raw: "head -c32 /dev/urandom | base64 > /opt/ansible-semaphore/semaphore_encryption_key"
  when: semaphore_encryption_key_result.stat.exists == False

- name: "Put encryption key in variable"
  set_fact:
    semaphore_encryption_key: "{{ lookup('file','/opt/ansible-semaphore/semaphore_encryption_key') }}"  

- name: "Set correct permissions of some file(s)"
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: '{{ item.mode }}'
  loop:
    - { path: '/opt/ansible-semaphore/semaphore_encryption_key', owner: 'root', group: 'root', mode: '0600' }

- name: "Install Ansible-Semaphore via .deb binary package from the internet"
  ansible.builtin.apt:
    deb: "https://github.com/ansible-semaphore/semaphore/releases/download/v{{ semui_deb_release }}/semaphore_{{ semui_deb_release }}_linux_amd64.deb"

- name: "Configure Ansible Semaphore by Transfering templates"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.mode}}"
    group: "{{ item.group }}"
    mode: '{{ item.mode }}'
  loop:
    - { src: 'templates/config-mysql.json.j2',
        dest: '/opt/ansible-semaphore/config.json',
        ower: 'root',
        group: 'root',
        mode: '0644',
        desc: 'Configure Ansible Semaphore UI'
        }  
    - { src: 'templates/semaphore.service.j2',
        dest: '/etc/systemd/system/semaphore.service',
        ower: 'root',
        group: 'root',
        mode: '0755',
        desc: 'Configure Systemd for Ansible Semaphore UI'
        }

- name: "Create initial local admin for Ansible Semaphore"
  ansible.builtin.command: semaphore user add --name '{{ semui_initial_name }}' --login '{{ semui_initial_login }}' --email '{{ semui_initial_email }}' --password '{{ semui_initial_pass }}' --admin --config /opt/ansible-semaphore/config.json
  when: semaphore_encryption_key_result.stat.exists == False
  
- name: "Start systemd service semaphore"
  ansible.builtin.systemd:
    name: semaphore
    state: started
    enabled: true
